#!/usr/bin/env node
/**
 * Generator: a synthetic markdown vault, written to disk, with zero private data.
 *
 * THIS IS AN EXAMPLE, NOT PART OF THE ENGINE. The hosted `/examples/tree/` demo
 * used to default to a data file built from someone's real notes — gitignored,
 * never published, and useless to anyone who does not have that file. This
 * script replaces it as the demo's data source: it writes real `.md` files, in
 * nested folders, using the exact conventions `markdown-tree.mjs` already reads
 * (`Up: [[Parent]]` + an inline `` `type: ...` `` tag) — so running the two
 * scripts back to back proves the adapter end to end, and the whole demo +
 * benchmark becomes reproducible by anyone with no data at all.
 *
 * It draws every random choice from the engine's own seeded RNG
 * (`src/util/rng.ts`, mulberry32). Same seed, same note count, same type
 * count → a byte-identical vault. That is the point: the demo is not "trust
 * me, it looked like this on my machine", it is "run this command".
 *
 * It never reads anything — no directory on this machine is opened. Every
 * name comes from small built-in, neutral word lists (below); nothing
 * personal, no real project or vault names, nothing recognisable.
 *
 * Usage:
 *   node synthetic-vault.mjs --out <dir> [--notes 2864] [--seed 20260824] \
 *        [--types 37] [--force]
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Rng } from '../../dist/src/util/rng.js';

const HELP =
  'usage: synthetic-vault.mjs --out <dir> [--notes 2864] [--seed 20260824] [--types 37] [--force]';

const args = parseArgs(process.argv.slice(2));
const outDir = args.out;
if (!outDir || args.help) {
  console.error(HELP);
  process.exit(outDir ? 0 : 2);
}

const noteCount = toInt(args.notes, 2864);
const seed = toInt(args.seed, 20260824);
const typeCount = toInt(args.types, 37);
const force = args.force === true;
const MAX_DEPTH = 6;

if (noteCount < 1) {
  console.error('--notes must be >= 1');
  process.exit(2);
}

// A non-empty target is refused by default. This script only ever writes and
// mkdirs — it never unlinks a file, with or without --force — so the guard
// exists purely to stop an accidental overwrite of something that was not
// generated by this script in the first place.
if (existsSync(outDir)) {
  const entries = readdirSync(outDir);
  if (entries.length > 0 && !force) {
    console.error(
      `refusing to write into non-empty directory ${outDir} (${entries.length} entries) — pass --force to proceed. this script never deletes anything.`,
    );
    process.exit(1);
  }
} else {
  mkdirSync(outDir, { recursive: true });
}

const rng = new Rng(seed);

// ------------------------------------------------------------- word lists

// Neutral, unrelated to any real project — natural-science and geography
// vocabulary, picked because it reads as plausible note titles without
// meaning anything.
const NOUNS = [
  'harbor', 'lattice', 'current', 'cascade', 'ember', 'quarry', 'reef', 'silo',
  'spindle', 'trellis', 'conduit', 'canopy', 'estuary', 'thicket', 'delta',
  'plateau', 'ridge', 'hollow', 'meadow', 'tundra', 'glacier', 'prairie',
  'marsh', 'dune', 'grove', 'bluff', 'cove', 'fjord', 'mesa', 'butte', 'moor',
  'fen', 'heath', 'steppe', 'tarn', 'glade', 'brook', 'creek', 'ravine',
  'gorge', 'canyon', 'cliff', 'shoal', 'atoll', 'isthmus', 'strait', 'channel',
  'basin', 'ledge', 'terrace',
];
const VERBS = [
  'gather', 'route', 'weigh', 'sort', 'bind', 'carry', 'fold', 'trace', 'span',
  'hold', 'shape', 'cast', 'drift', 'anchor', 'weave', 'chart', 'forge',
  'prune', 'seed', 'graft', 'kindle', 'temper', 'thread', 'gauge', 'mark',
  'split', 'merge', 'layer', 'stack', 'brace',
];
const WORD_POOL = [...NOUNS, ...VERBS];

// Root categories — obscure real fields, chosen only because they sound like
// a plausible knowledge base with no connection to any real project.
const DOMAINS = [
  'logistics', 'materials', 'hydrology', 'metallurgy', 'agronomy',
  'cartography', 'apiculture', 'sericulture', 'viticulture', 'forestry',
  'mineralogy', 'meteorology', 'oceanography', 'seismology', 'entomology',
  'mycology', 'pedology', 'glaciology', 'limnology', 'speleology',
];

const TYPE_WORDS = [
  'note', 'concept', 'process', 'index', 'log', 'reference', 'protocol',
  'measure', 'case', 'map', 'sample', 'cycle', 'layer', 'route', 'unit',
  'zone', 'grade', 'phase', 'trail', 'band', 'stage', 'form', 'class', 'rank',
  'field', 'chain', 'block', 'frame', 'shell', 'core', 'edge', 'seam', 'vein',
  'strand', 'knot', 'weave', 'span', 'crest', 'rift', 'vault',
];

const types = buildTypes(typeCount);

// ------------------------------------------------------------------- tree

const rootCount = Math.max(1, Math.min(DOMAINS.length, 7, noteCount));
const usedTitles = new Set();
const nodes = []; // { title, depth, parentIdx, type }
const pool = []; // preferential-attachment weight pool: node indices, duplicated by weight

for (let i = 0; i < rootCount; i++) {
  const title = titleCase(DOMAINS[i]);
  usedTitles.add(title);
  nodes.push({ title, depth: 0, parentIdx: null, type: pick(types), childCount: 0 });
  pool.push(i);
}

for (let i = rootCount; i < noteCount; i++) {
  // Preferential attachment: a node already in the pool multiple times (because
  // it has already gained children) is more likely to be picked again. That is
  // what produces the heavy tail — a handful of hub notes with many children,
  // most notes with one or none — instead of a flat, unrealistic tree.
  let parentIdx = null;
  for (let attempt = 0; attempt < 50; attempt++) {
    const candidate = pool[Math.floor(rng.next() * pool.length)];
    if (nodes[candidate].depth < MAX_DEPTH) {
      parentIdx = candidate;
      break;
    }
  }
  if (parentIdx === null) {
    // Every sampled candidate was already at MAX_DEPTH — fall back to a root
    // rather than looping forever or silently violating the depth cap.
    parentIdx = Math.floor(rng.next() * rootCount);
  }

  const title = uniqueTitle();
  const depth = nodes[parentIdx].depth + 1;
  nodes.push({ title, depth, parentIdx, type: pick(types), childCount: 0 });
  nodes[parentIdx].childCount++;
  const newIdx = nodes.length - 1;
  pool.push(parentIdx); // the parent just got heavier
  pool.push(newIdx); // and the new node enters the pool at baseline weight
}

// --------------------------------------------------------------- write it

let foldersCreated = 0;
let maxDepthSeen = 0;

for (const node of nodes) {
  const chain = ancestorChain(node);
  const folder = join(outDir, ...chain);
  if (chain.length > 0) mkdirSync(folder, { recursive: true });
  const filePath = join(folder, `${node.title}.md`);

  const lines = [];
  if (node.parentIdx !== null) lines.push(`Up: [[${nodes[node.parentIdx].title}]]`, '');
  lines.push(`\`type: ${node.type}\``, '', filler(node.title, node.type));
  writeFileSync(filePath, lines.join('\n') + '\n');

  if (node.depth > maxDepthSeen) maxDepthSeen = node.depth;
}
for (const node of nodes) if (node.childCount > 0) foldersCreated++;

console.log(
  [
    `notes written        ${nodes.length}`,
    `folders created      ${foldersCreated}`,
    `max depth            ${maxDepthSeen}`,
    `distinct types       ${new Set(nodes.map((n) => n.type)).size}`,
    `roots                ${rootCount}`,
    `seed                 ${seed}`,
    `output dir           ${outDir}`,
  ].join('\n'),
);

// -------------------------------------------------------------------- utils

function ancestorChain(node) {
  const chain = [];
  let cur = node;
  while (cur.parentIdx !== null) {
    cur = nodes[cur.parentIdx];
    chain.unshift(cur.title);
  }
  return chain;
}

function uniqueTitle() {
  for (let attempt = 0; attempt < 200; attempt++) {
    const a = WORD_POOL[Math.floor(rng.next() * WORD_POOL.length)];
    const b = WORD_POOL[Math.floor(rng.next() * WORD_POOL.length)];
    if (a === b) continue;
    const title = titleCase(a) + ' ' + titleCase(b);
    if (!usedTitles.has(title)) {
      usedTitles.add(title);
      return title;
    }
  }
  // Word-pair space exhausted (should not happen at any realistic --notes
  // count) — fall back to a numbered title rather than looping forever.
  let n = 1;
  let title;
  do {
    title = `Reserve Note ${n++}`;
  } while (usedTitles.has(title));
  usedTitles.add(title);
  return title;
}

function pick(arr) {
  return arr[Math.floor(rng.next() * arr.length)];
}

function titleCase(word) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function filler(title, type) {
  return `Placeholder content for the synthetic vault demo (type: ${type}). This note carries no information — it exists only to give the layout something to plot.`;
}

function buildTypes(n) {
  const out = [];
  for (let i = 0; i < n; i++) {
    out.push(
      i < TYPE_WORDS.length ? TYPE_WORDS[i] : `${TYPE_WORDS[i % TYPE_WORDS.length]}-${Math.floor(i / TYPE_WORDS.length) + 1}`,
    );
  }
  return out;
}

function toInt(v, fallback) {
  if (v === undefined || v === true) return fallback;
  const n = Number.parseInt(v, 10);
  return Number.isFinite(n) ? n : fallback;
}

function parseArgs(argv) {
  const o = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) continue;
    const key = a.slice(2);
    const next = argv[i + 1];
    if (next === undefined || next.startsWith('--')) o[key] = true;
    else {
      o[key] = next;
      i++;
    }
  }
  return o;
}
